import { list, put } from '@vercel/blob';

export type ProjectSnapshot = {
  version: 1;
  createdAt: string;
  updatedAt: string;
  files: Record<string, string>; // UTF-8 text only (v1)
};

function snapshotPathname(projectId: string) {
  return `projects/${projectId}/snapshot.json`;
}

export async function createEmptyProject(projectId: string) {
  const now = new Date().toISOString();
  const snapshot: ProjectSnapshot = {
    version: 1,
    createdAt: now,
    updatedAt: now,
    files: {
      'README.md': `# ${projectId}\n\nGenerated by Vibe Agent.\n`,
    },
  };
  await saveSnapshot(projectId, snapshot);
  return snapshot;
}

export async function loadSnapshot(projectId: string): Promise<ProjectSnapshot> {
  const pathname = snapshotPathname(projectId);
  const res = await list({ prefix: `projects/${projectId}/`, limit: 1000 });
  const hit = res.blobs.find((b) => b.pathname === pathname);
  if (!hit) {
    throw new Error('PROJECT_NOT_FOUND');
  }

  const r = await fetch(hit.url, { cache: 'no-store' });
  if (!r.ok) throw new Error(`SNAPSHOT_FETCH_FAILED_${r.status}`);
  const json = (await r.json()) as ProjectSnapshot;
  if (!json || json.version !== 1 || typeof json.files !== 'object') {
    throw new Error('SNAPSHOT_INVALID');
  }
  return json;
}

export async function saveSnapshot(projectId: string, snapshot: ProjectSnapshot) {
  snapshot.updatedAt = new Date().toISOString();
  const body = JSON.stringify(snapshot);
  await put(snapshotPathname(projectId), body, {
    access: 'public',
    addRandomSuffix: false,
    contentType: 'application/json',
    cacheControlMaxAge: 0,
  });
}

export function listPaths(snapshot: ProjectSnapshot): string[] {
  return Object.keys(snapshot.files).sort((a, b) => a.localeCompare(b));
}

